// <auto-generated />
using Abilities.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Abilities.Persistence.Migrations
{
    [DbContext(typeof(AbilitiesDbContext))]
    [Migration("20190825142341_SimplifyModelsStructure")]
    partial class SimplifyModelsStructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Abilities.Domain.Entities.BaseAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Abilities");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseAbility");
                });

            modelBuilder.Entity("Abilities.Domain.Entities.Ability", b =>
                {
                    b.HasBaseType("Abilities.Domain.Entities.BaseAbility");

                    b.HasDiscriminator().HasValue("Ability");
                });

            modelBuilder.Entity("Abilities.Domain.Entities.Ritual", b =>
                {
                    b.HasBaseType("Abilities.Domain.Entities.BaseAbility");

                    b.Property<int>("Tradition")
                        .HasColumnName("Tradition");

                    b.HasDiscriminator().HasValue("Ritual");
                });

            modelBuilder.Entity("Abilities.Domain.Entities.MysticalPower", b =>
                {
                    b.HasBaseType("Abilities.Domain.Entities.Ability");

                    b.Property<string>("Material");

                    b.HasDiscriminator().HasValue("MysticalPower");
                });

            modelBuilder.Entity("Abilities.Domain.Entities.Ability", b =>
                {
                    b.OwnsOne("Abilities.Domain.Entities.AbilityTier", "Adept", b1 =>
                        {
                            b1.Property<int>("AbilityId");

                            b1.Property<string>("Description")
                                .HasColumnName("AdeptDescription");

                            b1.Property<int>("Type")
                                .HasColumnName("AdeptType");

                            b1.HasKey("AbilityId");

                            b1.ToTable("Abilities");

                            b1.HasOne("Abilities.Domain.Entities.Ability")
                                .WithOne("Adept")
                                .HasForeignKey("Abilities.Domain.Entities.AbilityTier", "AbilityId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Abilities.Domain.Entities.AbilityTier", "Master", b1 =>
                        {
                            b1.Property<int>("AbilityId");

                            b1.Property<string>("Description")
                                .HasColumnName("MasterDescription");

                            b1.Property<int>("Type")
                                .HasColumnName("MasterType");

                            b1.HasKey("AbilityId");

                            b1.ToTable("Abilities");

                            b1.HasOne("Abilities.Domain.Entities.Ability")
                                .WithOne("Master")
                                .HasForeignKey("Abilities.Domain.Entities.AbilityTier", "AbilityId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Abilities.Domain.Entities.AbilityTier", "Novice", b1 =>
                        {
                            b1.Property<int>("AbilityId");

                            b1.Property<string>("Description")
                                .HasColumnName("NoviceDescription");

                            b1.Property<int>("Type")
                                .HasColumnName("NoviceType");

                            b1.HasKey("AbilityId");

                            b1.ToTable("Abilities");

                            b1.HasOne("Abilities.Domain.Entities.Ability")
                                .WithOne("Novice")
                                .HasForeignKey("Abilities.Domain.Entities.AbilityTier", "AbilityId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
